# Generated by Django 5.2.5 on 2025-08-25 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='2-20자 사이로 입력해주세요', max_length=20, null=True, verbose_name='닉네임')),
                ('profile_image', models.CharField(choices=[('default_1.png', '친근한 고양이'), ('default_2.png', '따뜻한 강아지'), ('default_3.png', '차분한 올빼미'), ('default_4.png', '활발한 토끼'), ('default_5.png', '지혜로운 여우')], default='images/profiles/default_1.png', max_length=40, verbose_name='프로필 이미지')),
                ('is_profile_complete', models.BooleanField(default=False, verbose_name='프로필 설정 완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
            },
        ),
    ]
