# Generated by Django 5.2.5 on 2025-08-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(choices=[('default_1.png', '친근한 고양이'), ('default_2.png', '따뜻한 강아지'), ('default_3.png', '차분한 올빼미'), ('default_4.png', '활발한 토끼'), ('default_5.png', '지혜로운 여우')], default='default_1.png', max_length=40, verbose_name='프로필 이미지'),
        ),
    ]
