# Generated by Django 5.2.5 on 2025-08-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(choices=[('default_1.png', 'default_1.png'), ('default_2.png', 'default_2.png'), ('default_3.png', 'default_3.png'), ('default_4.png', 'default_4.png'), ('default_5.png', 'default_5.png')], default='default_1.png', max_length=40, verbose_name='프로필 이미지'),
        ),
    ]
