# Generated by Django 5.2.5 on 2025-08-26 11:51

import characters.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='캐릭터명')),
                ('description', models.TextField(verbose_name='캐릭터 설명')),
                ('personality', models.TextField(verbose_name='성격 설정')),
                ('background_story', models.TextField(verbose_name='배경 이야기')),
                ('speaking_style', models.TextField(verbose_name='말투/대화 스타일')),
                ('tags', models.CharField(help_text='쉼표로 구분', max_length=200, verbose_name='태그들')),
                ('character_image', models.ImageField(blank=True, null=True, upload_to=characters.models.character_image_path, verbose_name='캐릭터 이미지')),
                ('visibility', models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='public', max_length=10, verbose_name='공개 설정')),
                ('status', models.CharField(choices=[('active', '활성'), ('pending', '검토 중'), ('suspended', '정지')], default='active', max_length=10, verbose_name='상태')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='총 대화 수')),
                ('rating_sum', models.IntegerField(default=0, verbose_name='평점 합계')),
                ('rating_count', models.IntegerField(default=0, verbose_name='평점 개수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotions.genre', verbose_name='장르')),
            ],
            options={
                'verbose_name': '캐릭터',
                'verbose_name_plural': '캐릭터들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='대화 제목')),
                ('status', models.CharField(choices=[('active', '진행 중'), ('paused', '일시 정지'), ('ended', '종료')], default='active', max_length=10, verbose_name='상태')),
                ('message_count', models.IntegerField(default=0, verbose_name='메시지 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시작일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 활동')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character', verbose_name='캐릭터')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '대화',
                'verbose_name_plural': '대화들',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', '사용자'), ('character', '캐릭터'), ('system', '시스템')], max_length=10, verbose_name='발신자')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('ai_model_used', models.CharField(blank=True, max_length=50, verbose_name='사용된 AI 모델')),
                ('generation_time', models.FloatField(blank=True, null=True, verbose_name='생성 시간(초)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='전송 시간')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='characters.conversation', verbose_name='대화')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지들',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_credits', models.IntegerField(default=50, verbose_name='무료 크레딧')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 크레딧',
                'verbose_name_plural': '사용자 크레딧들',
            },
        ),
        migrations.CreateModel(
            name='CharacterRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점')),
                ('review', models.TextField(blank=True, verbose_name='리뷰')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character', verbose_name='캐릭터')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '캐릭터 평점',
                'verbose_name_plural': '캐릭터 평점들',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'character')},
            },
        ),
    ]
