# Generated by Django 5.2.5 on 2025-09-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_usercredit_free_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredit',
            name='free_credits',
            field=models.IntegerField(default=5, verbose_name='무료 크레딧'),
        ),
    ]
