# Generated by Django 5.2.5 on 2025-08-26 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='감정명')),
                ('emoji', models.CharField(max_length=10, verbose_name='이모지')),
                ('color_code', models.CharField(default='#6366f1', max_length=7, verbose_name='색상코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('sub_description', models.CharField(blank=True, max_length=50, verbose_name='부제목')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성상태')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '감정',
                'verbose_name_plural': '감정들',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='장르명')),
                ('description', models.TextField(verbose_name='설명')),
                ('category', models.CharField(default='웹툰', max_length=30, verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '장르',
                'verbose_name_plural': '장르들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='작품명')),
                ('platform', models.CharField(max_length=50, verbose_name='플랫폼')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='평점')),
                ('thumbnail', models.URLField(blank=True, verbose_name='썸네일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotions.genre', verbose_name='장르')),
            ],
            options={
                'verbose_name': '작품',
                'verbose_name_plural': '작품들',
                'ordering': ['-rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EmotionGenreRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='우선순위')),
                ('reason', models.TextField(verbose_name='추천 이유')),
                ('match_percentage', models.IntegerField(default=80, verbose_name='매치율')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotions.emotion', verbose_name='감정')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotions.genre', verbose_name='장르')),
            ],
            options={
                'verbose_name': '감정-장르 추천',
                'verbose_name_plural': '감정-장르 추천들',
                'ordering': ['emotion', 'priority'],
                'unique_together': {('emotion', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='UserEmotionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('intensity', models.IntegerField(default=5, verbose_name='강도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotions.emotion', verbose_name='감정')),
                ('selected_genres', models.ManyToManyField(blank=True, to='emotions.genre', verbose_name='선택한 장르들')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 감정 기록',
                'verbose_name_plural': '사용자 감정 기록들',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
