# Generated by Django 5.2.5 on 2025-09-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='키워드')),
                ('weight', models.FloatField(default=1.0, verbose_name='가중치')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='키워드 설명')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotions.emotion', verbose_name='감정')),
            ],
            options={
                'verbose_name': '감정 키워드',
                'verbose_name_plural': '감정 키워드들',
                'ordering': ['emotion', '-weight', 'keyword'],
                'unique_together': {('emotion', 'keyword')},
            },
        ),
    ]
